# Tensor Basics

In [5]:
import torch

# Creating a simple 1D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print("1D Tensor:", tensor_1d)

# Creating a 2D tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n2D Tensor:")
print(tensor_2d)

# Tensor properties
print("\nShape of 2D tensor:", tensor_2d.shape)
print("Data type:", tensor_2d.dtype)

# Creating a tensor of zeros and ones
zeros = torch.zeros((3, 3))
ones = torch.ones((2, 4))
print("\nTensor of zeros:")
print(zeros)
print("\nTensor of ones:")
print(ones)


1D Tensor: tensor([1, 2, 3, 4, 5])

2D Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Shape of 2D tensor: torch.Size([2, 3])
Data type: torch.int64

Tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Tensor of ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [6]:
# Basic operations
sum_tensors = tensor_1d + torch.tensor([5, 4, 3, 2, 1])
print("\nSum of tensors:", sum_tensors)


Sum of tensors: tensor([6, 6, 6, 6, 6])


In [3]:
# Element-wise multiplication
product = tensor_2d * 2
print("\nElement-wise multiplication:")
print(product)



Element-wise multiplication:
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [4]:
# Matrix multiplication
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])
matrix_product = torch.matmul(matrix_a, matrix_b)
print("\nMatrix multiplication result:")
print(matrix_product)


Matrix multiplication result:
tensor([[19, 22],
        [43, 50]])


In [7]:
# Reshaping tensors
reshaped = tensor_2d.view(3, 2)
print("\nReshaped tensor:")
print(reshaped)


Reshaped tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [9]:
# Transposing tensors
transposed = tensor_2d.t()
print("\nTransposed tensor:")
print(transposed)


Transposed tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [23]:
print('tensor_2d',tensor_2d)

# Slicing tensors
sliced = tensor_2d[:, 1]
print("\nSecond column of 2D tensor:")
print(sliced)


print(':0',tensor_2d[:, 0])
print(':1',tensor_2d[:, 1])
print(':2',tensor_2d[:, 2])


print(':0',tensor_2d[0, :])
print(':1',tensor_2d[1, :])
# similar to what we do with numpy arrays

tensor_2d tensor([[1, 2, 3],
        [4, 5, 6]])

Second column of 2D tensor:
tensor([2, 5])
:0 tensor([1, 4])
:1 tensor([2, 5])
:2 tensor([3, 6])
:0 tensor([1, 2, 3])
:1 tensor([4, 5, 6])


In [24]:
# Stacking tensors
stacked = torch.stack((tensor_1d, tensor_1d))
print("\nStacked tensors:")
print(stacked)


Stacked tensors:
tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])


In [25]:
# Converting tensors to numpy
numpy_array = tensor_1d.numpy()
print("\nConverted to numpy array:")
print(numpy_array)



Converted to numpy array:
[1 2 3 4 5]


In [18]:
# Moving tensors to GPU (if available)
if torch.cuda.is_available():
    tensor_gpu = tensor_1d.to('cuda')
    print("\nTensor moved to GPU")
else:
    print('NO GPU')

NO GPU


In [5]:
import numpy as np
import torch
import time

# To show why tensor works better, we are creating a large list, NumPy array, and PyTorch tensor
size = 1000000
python_list = [i for i in range(size)]
numpy_array = np.array(python_list)
torch_tensor = torch.tensor(python_list)

# i am trying to show you a element-wise multiplication performance comparison
# Python list
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print(f"Python list time: {end - start:.5f} seconds")

# NumPy array
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print(f"NumPy array time: {end - start:.5f} seconds")

# PyTorch tensor
start = time.time()
torch_result = torch_tensor * 2
end = time.time()
print(f"PyTorch tensor time: {end - start:.5f} seconds")

# Broadcasting example
numpy_matrix = np.ones((3, 3))
torch_matrix = torch.ones((3, 3))

print("\nNumPy broadcasting:")
print(numpy_matrix + np.array([1, 2, 3]))

print("\nPyTorch broadcasting:")
print(torch_matrix + torch.tensor([1, 2, 3]))

# try this out 
# Python list time: 0.45487 seconds
# NumPy array time: 0.02181 seconds
# PyTorch tensor time: 0.08847 seconds

Python list time: 0.05997 seconds
NumPy array time: 0.00270 seconds
PyTorch tensor time: 0.00213 seconds

NumPy broadcasting:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]

PyTorch broadcasting:
tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])


In [ ]:
# GPU acceleration with PyTorch (if available) # this would show you how fast a tensor is better
if torch.cuda.is_available():
    device = torch.device('cuda')
    torch_tensor_gpu = torch.tensor(python_list, device=device)
    start = time.time()
    torch_result_gpu = torch_tensor_gpu * 2
    end = time.time()
    print(f"PyTorch tensor on GPU time: {end - start:.5f} seconds")
else:
    print("GPU not available")


# Some sample cases where we will use these Tensor.
### just showing some examples, we will learn about how to write these in details in upcoming classes  

In [14]:
import torch
import torch.nn.functional as F

# Simulating a simple artificial neuron

def simple_neuron(inputs, weights, bias):
    # Convert inputs and weights to tensors
    inputs = torch.tensor(inputs, dtype=torch.float32)
    weights = torch.tensor(weights, dtype=torch.float32)
    bias = torch.tensor(bias, dtype=torch.float32)

    # Weighted sum of inputs and weights + bias
    z = torch.dot(inputs, weights) + bias

    # Applying activation function (Sigmoid)
    output = torch.sigmoid(z)

    return output

# Example inputs, weights, and bias
inputs = [0.5, 0.8, 0.3]
weights = [0.4, 0.7, 0.2]
bias = 0.1

# Get the neuron's output
output = simple_neuron(inputs, weights, bias)
print(f"Neuron Output: {output.item():.4f}")

Neuron Output: 0.7150


In [6]:
import torch
import torch.nn as nn
import torch.optim as optim

# Representing data with tensors
# Simulating a dataset: 100 samples, 3 features
X = torch.rand((100, 3))  # Inputs
y = torch.randint(0, 2, (100,))  # Binary labels

# Building a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(3, 5)
        self.fc2 = nn.Linear(5, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

# Initializing model, loss, and optimizer
model = SimpleNN()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
epochs = 5
for epoch in range(epochs):
    # Forward pass
    outputs = model(X).squeeze()
    loss = criterion(outputs, y.float())

    # Backward pass
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# Batch processing
batch_size = 10
for i in range(0, len(X), batch_size):
    X_batch = X[i:i+batch_size]
    y_batch = y[i:i+batch_size]
    batch_output = model(X_batch)
    print(f"Batch {i//batch_size + 1} Output: {batch_output.squeeze().detach()}")


Epoch [1/5], Loss: 0.6895
Epoch [2/5], Loss: 0.6895
Epoch [3/5], Loss: 0.6895
Epoch [4/5], Loss: 0.6894
Epoch [5/5], Loss: 0.6894
Batch 1 Output: tensor([0.5500, 0.5367, 0.5157, 0.5336, 0.5293, 0.5273, 0.5307, 0.5287, 0.5266,
        0.5167])
Batch 2 Output: tensor([0.5222, 0.5384, 0.5259, 0.5208, 0.5242, 0.5262, 0.5318, 0.5038, 0.5164,
        0.5307])
Batch 3 Output: tensor([0.5267, 0.5124, 0.5179, 0.5260, 0.5167, 0.5182, 0.5070, 0.5336, 0.5261,
        0.5124])
Batch 4 Output: tensor([0.5287, 0.5260, 0.5333, 0.5316, 0.5330, 0.5214, 0.5442, 0.5182, 0.5291,
        0.5459])
Batch 5 Output: tensor([0.5178, 0.5329, 0.5289, 0.5373, 0.5283, 0.5075, 0.5377, 0.5221, 0.5296,
        0.5280])
Batch 6 Output: tensor([0.5230, 0.5344, 0.5304, 0.5277, 0.5341, 0.5069, 0.5363, 0.5240, 0.5323,
        0.5326])
Batch 7 Output: tensor([0.5245, 0.5328, 0.5257, 0.5253, 0.5278, 0.5144, 0.5127, 0.5174, 0.5084,
        0.5097])
Batch 8 Output: tensor([0.5247, 0.5310, 0.5314, 0.5341, 0.5317, 0.5335, 0.5136,

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Loading the California Housing dataset
california = fetch_california_housing()
X, y = california.data, california.target

# Standardizing the data
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = y.reshape(-1, 1)

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Converting to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# 2. Building a simple regression model
class RegressionNN(nn.Module):
    def __init__(self):
        super(RegressionNN, self).__init__()
        self.fc1 = nn.Linear(X_train.shape[1], 10)
        self.fc2 = nn.Linear(10, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 3. Initializing model, loss, and optimizer
model = RegressionNN()
criterion = nn.MSELoss()  # Mean Squared Error Loss for regression
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 4. Training loop
epochs = 20
for epoch in range(epochs):
    model.train()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# 5. Evaluation
model.eval()
y_pred = model(X_test).detach()
mse = criterion(y_pred, y_test)
print(f"Test MSE: {mse.item():.4f}")


Epoch [1/20], Loss: 5.0021
Epoch [2/20], Loss: 4.7320
Epoch [3/20], Loss: 4.4798
Epoch [4/20], Loss: 4.2441
Epoch [5/20], Loss: 4.0239
Epoch [6/20], Loss: 3.8182
Epoch [7/20], Loss: 3.6260
Epoch [8/20], Loss: 3.4464
Epoch [9/20], Loss: 3.2786
Epoch [10/20], Loss: 3.1218
Epoch [11/20], Loss: 2.9753
Epoch [12/20], Loss: 2.8384
Epoch [13/20], Loss: 2.7104
Epoch [14/20], Loss: 2.5907
Epoch [15/20], Loss: 2.4788
Epoch [16/20], Loss: 2.3741
Epoch [17/20], Loss: 2.2761
Epoch [18/20], Loss: 2.1844
Epoch [19/20], Loss: 2.0983
Epoch [20/20], Loss: 2.0175
Test MSE: 2.0116
