# Python Basics

In [ ]:
# Anaconda installation 

In [ ]:
# Environment setup

In [ ]:
-------------------------------------# NumPy

#     NumPy (Numerical Python) is a fundamental library for numerical and scientific computing in Python. 
#     It provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical
#     functions to perform operations on these arrays efficiently. NumPy is often the foundation of other data 
#     science libraries, as it offers fast computation and vectorized operations.

------------------------# Pandas----------------------------------------

#     Pandas is a powerful library for data manipulation and analysis. 
#     It provides data structures like DataFrames and Series, which are essential for organizing, 
#     filtering, and cleaning large datasets. Pandas makes it easy to read data from different file formats, 
#     such as CSV and Excel, and supports a variety of data operations to transform raw data into an analyzable format.
    

----------------------------------------#SciPy

#     SciPy is an open-source library that builds on NumPy to provide advanced mathematical, 
#     scientific, and statistical functions. It is widely used for tasks like optimization, integration, 
#     and statistical analysis. The stats module within SciPy contains functions for probability distributions, 
#     hypothesis testing, and statistical metrics, making it essential for data analysis and scientific computing.

Statsmodels

#     Statsmodels is a library that provides classes and functions for the estimation of many different statistical 
#     models, performing statistical tests, and conducting data exploration. It’s particularly useful for regression
#     analysis and econometric modeling, and it complements SciPy and Pandas by adding more specialized statistical
#     tools, especially for hypothesis testing and time-series analysis.

Scikit-Learn 

#     Scikit-Learn is one of the most widely used machine learning libraries in Python. 
#     It offers a rich set of tools for building machine learning models, including algorithms for classification,
#     regression, clustering, and dimensionality reduction. Scikit-Learn is known for its simple and consistent API, 
#     which makes it easy to build, evaluate, and fine-tune machine learning models for predictive data analysis.

Matplotlib

#     Matplotlib is a foundational plotting library for creating static, animated, and interactive visualizations in 
#     Python. It provides control over basic visual elements, such as lines, bars, and labels, which makes it 
#     versatile for data visualization tasks. Many other visualization libraries build on Matplotlib's structure, 
#     providing additional features and improved visual aesthetics.

Seaborn

#     Seaborn is a visualization library built on top of Matplotlib, designed to make it easier to create 
#     aesthetically pleasing and informative statistical graphics. It provides a high-level interface for 
#     drawing attractive graphs, especially for exploring relationships between variables and visualizing 
#     distributions. Seaborn's syntax simplifies creating complex visualizations with just a few lines of code.

Plotly

#     Plotly is an interactive graphing library that allows for the creation of dynamic and web-based visualizations. 
#     Plotly Express is a high-level interface for quickly generating Plotly charts, including scatter plots, bar 
#     charts, and 3D graphs. Unlike static libraries, Plotly supports zooming, hovering, and real-time updates, 
#     making it ideal for interactive data visualization and dashboarding.

In [2]:
# NumPy Lecture - Jupyter Notebook

# Advantages of NumPy
"""
Advantages of NumPy:
1. Faster computations compared to Python lists due to optimized C backend.
2. Supports multidimensional arrays.
3. Wide range of mathematical functions.
4. Easy array manipulations: slicing, indexing, and reshaping.
5. Essential for scientific computing and data analysis.
"""

# NumPy: Installation and Import
# Install NumPy if not already installed (Uncomment the following line to run)
# !pip install numpy

# Importing NumPy
import numpy as np

# Creating NumPy Arrays
# Creating 1D, 2D, and 3D NumPy arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)
print("3D Array:\n", array_3d)

# Explanation of Attributes
print("Array Shape:", array_2d.shape)
print("Array Data Type:", array_1d.dtype)
print("Number of Dimensions:", array_3d.ndim)
print("Array Size:", array_2d.size)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array Shape: (2, 3)
Array Data Type: int64
Number of Dimensions: 3
Array Size: 6


In [3]:
# NumPy Array Functions
# Basic operations on NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
# Addition
print("Addition:", np.add(a, b))

Addition: [5 7 9]


In [5]:
# Subtraction
print("Subtraction:", np.subtract(a, b))

Subtraction: [-3 -3 -3]


In [6]:
# Multiplication
print("Multiplication:", np.multiply(a, b))

Multiplication: [ 4 10 18]


In [7]:
# Division
print("Division:", np.divide(a, b))

Division: [0.25 0.4  0.5 ]


In [ ]:
# Power of
print("Power:", np.power(a, 2))

In [8]:
# Calculating Median, Mean, Standard Deviation, and Variance
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Median:", np.median(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Median: 5.0
Mean: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


In [51]:
# Calculating Percentiles 
# The 25th percentile is the value at which 25% of the answers lie below that value, and 75% of the answers lie above that value
print("25th Percentile:", np.percentile(arr, 25))
print("75th Percentile:", np.percentile(arr, 75))

25th Percentile: 3.0
75th Percentile: 7.0


In [10]:
# String Functions in NumPy
names = np.array(["Alice", "Bob", "Charlie"])
print("Upper Case:", np.char.upper(names))
print("Lower Case:", np.char.lower(names))
print("Title Case:", np.char.title(names))

Upper Case: ['ALICE' 'BOB' 'CHARLIE']
Lower Case: ['alice' 'bob' 'charlie']
Title Case: ['Alice' 'Bob' 'Charlie']


In [11]:
# Access 1D NumPy Array Elements
print("Access 1st Element:", array_1d[0])
print("Access Last Element:", array_1d[-1])

Access 1st Element: 1
Access Last Element: 5


In [12]:
# Access 2D NumPy Array Elements
print("Access Element (1, 2):", array_2d[1, 2])

Access Element (1, 2): 6


In [13]:
# Access 3D NumPy Array Elements
print("Access Element (0, 1, 1):", array_3d[0, 1, 1])

Access Element (0, 1, 1): 4


In [14]:
# Negative Indexing
print("Access Last Element Using Negative Index:", array_1d[-1])

Access Last Element Using Negative Index: 5


In [15]:
# Slicing 1D NumPy Arrays
print("Slice 1D Array [1:4]:", array_1d[1:4])

Slice 1D Array [1:4]: [2 3 4]


In [16]:
# Slicing Using Step Value
print("Slice with Step [::2]:", array_1d[::2])

Slice with Step [::2]: [1 3 5]


In [17]:
# Slicing: 2D Array
print("Slice 2D Array (Rows 0 to 1, All Columns):\n", array_2d[0:2, :])

Slice 2D Array (Rows 0 to 1, All Columns):
 [[1 2 3]
 [4 5 6]]


In [18]:
# Slicing: 3D Array
print("Slice 3D Array (First Matrix, First Row):", array_3d[0, 0, :])

Slice 3D Array (First Matrix, First Row): [1 2]


In [19]:
# Negative Slicing
print("Negative Slicing (Last 3 Elements):", array_1d[-3:])

Negative Slicing (Last 3 Elements): [3 4 5]


In [ ]:
# Accessing elements 

In [21]:
# Accessing Elements from 2D Array
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(array_2d)

# Access a single element
print("Element at Row 0, Column 1:", array_2d[0, 1]) 
print("Element at Row 2, Column 0:", array_2d[2, 0]) 

# Access the last element of a specific row
print("Last element of Row 1:", array_2d[1, -1]) 
# Access an element using negative indexing
print("Element at Row -1, Column -2:", array_2d[-1, -2]) 

# Access elements from different rows and columns using slicing
print("Row 1, Columns 0 to 2:", array_2d[1, 0:3])  
print("Rows 0 to 1, Column 2:", array_2d[0:2, 2]) 


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at Row 0, Column 1: 20
Element at Row 2, Column 0: 70
Last element of Row 1: 60
Element at Row -1, Column -2: 80
Row 1, Columns 0 to 2: [40 50 60]
Rows 0 to 1, Column 2: [30 60]


In [23]:
# Accessing Elements from 3D Array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(array_3d)

# Access a single element
print("Element at Block 0, Row 1, Column 1:", array_3d[0, 1, 1])  
print("Element at Block 2, Row 0, Column 0:", array_3d[2, 0, 0])  

# Access the last element of a specific block
print("Last element of Block 1:", array_3d[1, -1, -1]) 

# Access an element using negative indexing
print("Element at Block -1, Row -2, Column -2:", array_3d[-1, -2, -2])  

# Access all elements in a specific row of a block
print("All elements in Row 0 of Block 2:", array_3d[2, 0, :]) 

# Access all rows and columns of a specific block
print("All rows and columns of Block 1:\n", array_3d[1, :, :])

# Access specific rows and columns across multiple blocks
print("Elements from all blocks at Row 0, Column 1:", array_3d[:, 0, 1]) 


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Element at Block 0, Row 1, Column 1: 4
Element at Block 2, Row 0, Column 0: 9
Last element of Block 1: 8
Element at Block -1, Row -2, Column -2: 9
All elements in Row 0 of Block 2: [ 9 10]
All rows and columns of Block 1:
 [[5 6]
 [7 8]]
Elements from all blocks at Row 0, Column 1: [ 2  6 10]


In [24]:
# Ask students

# 2D Array Example
array_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(array_2d)
# Access the middle element of the array (Row 1, Column 1)
print("Middle element of the 2D array:", array_2d[1, 1]) 

# Access the entire first column (all rows, column 0)
print("First column:", array_2d[:, 0]) 

# Access the entire last row
print("Last row:", array_2d[-1, :]) 

# Access a sub-matrix (top-left 2x2 matrix)
print("Sub-matrix (top-left 2x2):\n", array_2d[0:2, 0:2])


Middle element of the 2D array: 25
First column: [ 5 20 35]
Last row: [35 40 45]
Sub-matrix (top-left 2x2):
 [[ 5 10]
 [20 25]]


In [29]:
# 3D Array Example
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]],
])

print(array_3d)

# Access the element at Block 2, Row 1, Column 2
print("Block 2, Row 1, Column 2:", array_3d[2, 1, 2]) 

# Access all elements in the second row of all blocks
print("Second row of all blocks:\n", array_3d[:, 1, :])


# Access the last two elements of the first row in Block 0
print("Last two elements of the first row in Block 0:", array_3d[0, 0, -2:])
print("Access 1st elements of the first row in Block 0:", array_3d[0, 0, :-2])

# Extract a sub-cube (Top-left 2x2x2 of the 3D array)
print("Sub-cube (top-left 2x2x2):\n", array_3d[0:2, 0:2, 0:2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Block 2, Row 1, Column 2: 24
Second row of all blocks:
 [[ 4  5  6]
 [13 14 15]
 [22 23 24]]
Last two elements of the first row in Block 0: [2 3]
Access 1st elements of the first row in Block 0: [1]
Sub-cube (top-left 2x2x2):
 [[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]]


In [ ]:
# Some string operations

In [31]:
import numpy as np

# Creating a NumPy array of strings
names = np.array(["Alice", "Bob", "Charlie"])

In [32]:
# 1. Convert strings to upper case
upper_case = np.char.upper(names)
print("Upper Case:", upper_case)

Upper Case: ['ALICE' 'BOB' 'CHARLIE']


In [33]:
# 2. Convert strings to lower case
lower_case = np.char.lower(names)
print("Lower Case:", lower_case) 

Lower Case: ['alice' 'bob' 'charlie']


In [34]:
# 3. Title-case each string
title_case = np.char.title(names)
print("Title Case:", title_case) 

Title Case: ['Alice' 'Bob' 'Charlie']


In [35]:
# 4. Add a prefix or suffix to each string
prefixed = np.char.add("Dr. ", names)
print("Prefixed:", prefixed)  

suffixed = np.char.add(names, " Jr.")
print("Suffixed:", suffixed) 

Prefixed: ['Dr. Alice' 'Dr. Bob' 'Dr. Charlie']
Suffixed: ['Alice Jr.' 'Bob Jr.' 'Charlie Jr.']


In [39]:
# 5. Replace substrings in strings
replaced = np.char.replace(names, "o", "OS")
print("Replace 'o' with 'OS':", replaced)  

Replace 'o' with 'OS': ['Alice' 'BOSb' 'Charlie']


In [40]:
# 6. Check if strings start with a specific prefix
starts_with = np.char.startswith(names, "A")
print("Starts with 'A':", starts_with)  

Starts with 'A': [ True False False]


In [41]:
# 7. Split strings into lists of words
split = np.char.split(names)
print("Split Strings:", split)

Split Strings: [list(['Alice']) list(['Bob']) list(['Charlie'])]


In [42]:
# 8. Join strings with a specific separator
joined = np.char.join("-", names)
print("Joined with '-':", joined)  

Joined with '-': ['A-l-i-c-e' 'B-o-b' 'C-h-a-r-l-i-e']


In [43]:
# 9. Center align strings with padding
centered = np.char.center(names, 10, fillchar="*")
print("Centered Strings:", centered)

Centered Strings: ['**Alice***' '***Bob****' '*Charlie**']


In [44]:
# 10. Strip unwanted characters (trimming)
stripped = np.char.strip(np.array(["  Alice  ", " Bob\t", "\nCharlie"]))
print("Stripped Strings:", stripped)  

Stripped Strings: ['Alice' 'Bob' 'Charlie']


In [45]:
# 11. Concatenate strings
concatenated = np.char.add(names, " is awesome!")
print("Concatenated Strings:", concatenated)

Concatenated Strings: ['Alice is awesome!' 'Bob is awesome!' 'Charlie is awesome!']


In [50]:
# 12. Count occurrences of a substring
count = np.char.count(names, "i")
print("Count 'o' in each name:", count) 

Count 'o' in each name: [1 0 1]


In [ ]:
# Some more operations

In [52]:
#Convert strings to uppercase and title case:
import numpy as np
array = np.array(["python", "numpy", "string", "functions"])

# Uppercase
upper_case = np.char.upper(array)
print("Uppercase:", upper_case) 

# Title case
title_case = np.char.title(array)
print("Title case:", title_case) 


Uppercase: ['PYTHON' 'NUMPY' 'STRING' 'FUNCTIONS']
Title case: ['Python' 'Numpy' 'String' 'Functions']


In [53]:
# Add prefix and suffix:
array = np.array(["Data Science", "Machine Learning", "Artificial Intelligence"])

# Add prefix
prefixed = np.char.add("Field: ", array)
print("Prefixed:", prefixed)

# Add suffix
suffixed = np.char.add(array, " is fascinating!")
print("Suffixed:", suffixed)



Prefixed: ['Field: Data Science' 'Field: Machine Learning'
 'Field: Artificial Intelligence']
Suffixed: ['Data Science is fascinating!' 'Machine Learning is fascinating!'
 'Artificial Intelligence is fascinating!']


In [54]:
# Check if strings start with a specific letter:
array = np.array(["Alice", "Bob", "Charlie", "Eve"])
starts_with_a = np.char.startswith(array, "A")
print("Starts with 'A':", starts_with_a) 


Starts with 'A': [ True False False False]


In [55]:
#Replace a character and count occurrences: 
array = np.array(["hello", "world", "numpy", "practice"])

# Replace 'o' with 'OO'
replaced = np.char.replace(array, "o", "OO")
print("Replaced 'o' with 'OO':", replaced)


# Count occurrences of 'p'
count_p = np.char.count(array, "p")
print("Count of 'p':", count_p)  

Replaced 'o' with 'OO': ['hellOO' 'wOOrld' 'numpy' 'practice']
Count of 'p': [0 0 1 1]


In [56]:
#Split and join strings:
array = np.array(["apple", "banana", "cherry", "date", "elderberry"])

# Split each string
split_strings = np.char.split(array)
print("Split strings:", split_strings)

# Join characters with '-'
joined = np.char.join("-", array)
print("Joined strings:", joined)



Split strings: [list(['apple']) list(['banana']) list(['cherry']) list(['date'])
 list(['elderberry'])]
Joined strings: ['a-p-p-l-e' 'b-a-n-a-n-a' 'c-h-e-r-r-y' 'd-a-t-e' 'e-l-d-e-r-b-e-r-r-y']


In [57]:
#Trim and center strings:
array = np.array(["  Trim  ", "Spaces ", " From Strings ", " In  Arrays  "])

# Strip unnecessary spaces
stripped = np.char.strip(array)
print("Stripped strings:", stripped)

# Center align with padding
centered = np.char.center(stripped, 20, fillchar="#")
print("Centered strings:", centered)



Stripped strings: ['Trim' 'Spaces' 'From Strings' 'In  Arrays']
Centered strings: ['########Trim########' '#######Spaces#######' '####From Strings####'
 '#####In  Arrays#####']


In [58]:
#Split and count words:
array = np.array(["python programming", "data analysis", "machine learning"])

# Split into words
split_words = np.char.split(array)
print("Split into words:", split_words)

# Count occurrences of 'data'
count_data = np.char.count(array, "data")
print("Count of 'data':", count_data)  


Split into words: [list(['python', 'programming']) list(['data', 'analysis'])
 list(['machine', 'learning'])]
Count of 'data': [0 1 0]


In [59]:
#Find string length and replace words:

array = np.array(["welcome", "to", "numpy", "string", "manipulation"])

# Length of each string
string_length = np.char.str_len(array)
print("String lengths:", string_length) 

# Replace 'string' with 'text'
replaced = np.char.replace(array, "string", "text")
print("Replaced 'string' with 'text':", replaced)

String lengths: [ 7  2  5  6 12]
Replaced 'string' with 'text': ['welcome' 'to' 'numpy' 'text' 'manipulation']


In [64]:
#Extract and modify email domains:

emails = np.array(["user1@gmail.com", "user2@yahoo.com", "user3@hotmail.com"])

# Extract domains
domains = np.char.split(emails, "@")
print(domains)
domains = [email[1] for email in domains]
print("Domains:", domains)  

# Replace 'hotmail.com' with 'outlook.com'
updated_emails = np.char.replace(emails, "hotmail.com", "outlook.com")
print("Updated emails:", updated_emails)

[list(['user1', 'gmail.com']) list(['user2', 'yahoo.com'])
 list(['user3', 'hotmail.com'])]
Domains: ['gmail.com', 'yahoo.com', 'hotmail.com']
Updated emails: ['user1@gmail.com' 'user2@yahoo.com' 'user3@outlook.com']


In [ ]:
# Please try doing this 

# 1 Create a NumPy array of strings: ["python", "numpy", "string", "functions"].

#     Convert all strings to uppercase.
#     Convert all strings to title case.


# 2 Given a NumPy array: ["Data Science", "Machine Learning", "Artificial Intelligence"],

#     Add the prefix "Field: " to each string.
#     Add the suffix " is fascinating!" to each string.

# 3 Write a program to check if the strings in the array ["Alice", "Bob", "Charlie", "Eve"] start with the letter "A".

# 4 Create a NumPy array with the strings: ["hello", "world", "numpy", "practice"].

#     Replace the letter "o" with "OO" in all strings.
#     Count the occurrences of the letter "p" in each string.

# 5 Create a NumPy array: ["apple", "banana", "cherry", "date", "elderberry"].

#     Split each string into a list of characters.
#     Join each string’s characters using a - separator.

# 6 Create a NumPy array: [" Trim ", "Spaces ", " From Strings ", " In Arrays "].

#     Strip all unnecessary spaces from each string.
#     Center-align the strings with a total width of 20 and fill the extra spaces with "#".